### ISSUE TITLE
Use Renovate to update this repository?

### ISSUE THREAD

**Issue by HonkingGoose** [MShekow/renovate-pr-visualization#4]
It's probably a good idea to update your dependencies with Renovate. Then you can see if newer dependencies break things, via automated tests or manual checks.

Or is this the kind of project that a user should fork and update themselves?

**Comment by MShekow** [comment]
The reason I've not yet added Renovate to this repo yet, is that I estimate a high complexity for adding _useful_ tests (which are mostly of the _end-to-end_ kind, due to interacting with SaaS services). Because of that high level of complexity, I'm hesitant to start implementing these tests _now_, because I'm currently focusing my spare time on implementing two other OSS projects. Adding Renovate now would only add lots of mails to my email inbox, without any real benefit. Other users can of course contribute end-to-end tests if they'd like ;).

**Comment by HonkingGoose** [comment]
Thanks for the response! I don't know enough to write tests. So I'll let you, or somebody else write tests. And I suspect you already know how to get a basic Renovate config going for this repository. 😄
